### ISSUE TITLE
在多个GPU上采样失败。

### ISSUE THREAD

**Issue by luoshmg** [CHAINNEVERLIU/Pytorch-DDPM#2]
在1个GPU上可以顺利执行`image_test.py`，最后生成了一张图片。

但是在4个GPU上执行时，报错：

Traceback (most recent call last):
  File "/home/ubuntu/dev/Pytorch-DDPM/DiffusionModels/image_test.py", line 103, in <module>
    samples = DDPM(mode="generate", image_size=image_size, batch_size=64, channels=channels)
  File "/data/miniconda3/envs/diffusion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/miniconda3/envs/diffusion/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/data/miniconda3/envs/diffusion/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data/miniconda3/envs/diffusion/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/data/miniconda3/envs/diffusion/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AssertionError: Caught AssertionError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data/miniconda3/envs/diffusion/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/data/miniconda3/envs/diffusion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/dev/Pytorch-DDPM/DiffusionModels/diffusionModels/simpleDiffusion/simpleDiffusion.py", line 127, in forward
    return self.sample(image_size=kwargs["image_size"],
  File "/data/miniconda3/envs/diffusion/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/dev/Pytorch-DDPM/DiffusionModels/diffusionModels/simpleDiffusion/simpleDiffusion.py", line 105, in sample
    return self.p_sample_loop(shape=(batch_size, channels, image_size, image_size))
  File "/data/miniconda3/envs/diffusion/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/dev/Pytorch-DDPM/DiffusionModels/diffusionModels/simpleDiffusion/simpleDiffusion.py", line 90, in p_sample_loop
    assert list(self.denoise_model.parameters()), "model.parameters() is empty"
AssertionError: model.parameters() is empty

除了在`DDPM.to(device)`后面加了一行`DDPM = nn.DataParallel(DDPM)`以外，代码基本没变。

**Comment by luoshmg** [comment]
在`samples = DDPM(...)`语句之前加一句`DDPM = DDPM.module`就不报错了。但缺点是这样就不能多张卡并行采样了。
